### ISSUE TITLE
Implement status formatting.

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-cli#106]
Status command output is printed as is in the old CLI.
It should be printed in some human-readable way.

See https://github.com/rabbitmq/rabbitmq-cli/blob/master/lib/rabbitmq/cli/ctl/status_print.ex

**Comment by michaelklishin** [comment]
This defaults to the Erlang terms output for maximum compatibility. We can produce something human-readable for `3.8.0`.

**Comment by michaelklishin** [comment]
Of course, the above is not to say that I find the current format fine but our top goals for the `3.7.0` version is compatibility with existing tooling and extensibility. The community can come up with their own formatters and  distribute them as plugins, and we will change the default over time. Some will consider JSON formatting to be more valuable than a "human-readable" one, for example.
