### ISSUE TITLE
Make `switches/0` an optional callback

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-cli#120]
After https://github.com/rabbitmq/rabbitmq-cli/commit/59ba4d91b379fb76e829f7d037f6c9a04146e34f it becomes confusing that some commands won't have to define any switches since they only support `-p [vhost]` (which is auto-defined by the tool).

[delete-shovel](https://github.com/rabbitmq/rabbitmq-shovel/blob/master/src/Elixir.RabbitMQ.CLI.Ctl.Commands.DeleteShovelCommand.erl#L41) is a good example of this.

The `switches/0` callback therefore should probably be made optional.

**Comment by hairyhum** [comment]
We can add `aliases/0` to that.

**Comment by michaelklishin** [comment]
#124 was reverted. Please resubmit without the global parser change (which has a serious flaw: https://github.com/rabbitmq/rabbitmq-cli/issues/126).
