### ISSUE TITLE
List non AMQP connections

### ISSUE THREAD

**Issue by carlhoerberg** [rabbitmq/rabbitmq-cli#121]
`rabbitmqctl list_connections` only reports AMQP connections, not MQTT nor STOMP connections.

**Comment by michaelklishin** [comment]
We decided to go with separate commands for MQTT, STOMP, and so on for a couple of reasons:

 * If you don't have said plugins enabled, it would be weird to attempt to support those connections in CLI tools
 * Info keys (this is RabbitMQ internals speak, means pieces of information) for those connections will be different from AMQP 0-9-1, so it makes sense to let the user specify them, which doesn't fit `list_connections`

So there will be CLI extensions in various plugin repos that provide `list_mqtt_connections`, `list_stomp_connections`, and so on.

**Comment by michaelklishin** [comment]
This was done for MQTT, STOMP, and AMQP 1.0.
