### ISSUE TITLE
Tools to streamify command execution

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-cli#136]
Some commands (e.g. `wait`, `enable_plugins`, `node_health_check`) can have several steps, which can be logged in the command output via elixir [Stream](http://elixir-lang.org/docs/stable/elixir/Stream.html).

This steps can have execution errors and require specific exit codes, so stream processing should support that.

It would be nice for formatter implementations to be able to avoid matching `{:error, _}` in stream formatting.

**Comment by binarin** [comment]
I think that for `node_health_check` it would be even better if checks are performed in parallel. And each of this parallel computations should keep track of timeouts themselves, so it will have an opportunity to report the offending queue/channel/...

**Comment by michaelklishin** [comment]
I believe the formatter/stream handling we have today is decent, and there haven't been more specific ideas to make this a pressing issue in three years => closing.
