### ISSUE TITLE
Consider adding a command that deletes a queue

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-cli#143]
It's a fairly common request from ops. We should also consider a command that forcefully deletes a queue, e.g. using `rabbit_amqqueue:internal_delete/1` or similar (see [this rabbitmq-users thread](https://groups.google.com/forum/#!searchin/rabbitmq-users/James$20Rybicki%7Csort:date/rabbitmq-users/rpO3dFzm-yQ/Gff6EmbjCAAJ) for some examples).

Suggested by @Gsantomaggio.

**Comment by hairyhum** [comment]
Can this command be a part of `rabbitmq_admin` tool? To mimic `rabbitmqadmin`, but with CLI.

**Comment by michaelklishin** [comment]
I don't know if we want to reinvent `rabbitmqadmin`. If we do it should have a distinct enough name.

**Comment by Gsantomaggio** [comment]
Now there is the command `purge_queue` and using a script it is possible to purges all queues in a vhost. ( see rabbitmq-cli/issues/146 )

In the same way It would be enough add the command `delete_queue`, and using a script it would be possible to remove one or more queues ( see #145)

**Comment by michaelklishin** [comment]
@Gsantomaggio yes but it would be more convenient (or dangerous, depending on who you ask) if the tool did the iteration.

**Comment by michaelklishin** [comment]
Resolved in 0b26ccafed7deb32f93260713916412212d18ea2.

**Comment by Gsantomaggio** [comment]
:heart:
