### ISSUE TITLE
Implement the hipe_compile command

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-cli#178]
Originally contributed in https://github.com/rabbitmq/rabbitmq-server/pull/808, it slipped under the radar.

**Comment by michaelklishin** [comment]
So this one is quite tricky in 3.7.0: we don't want to add a server dependency to CLI tools, so perhaps this should be an optional plugin that depends on it. @binarin WDYT?

**Comment by michaelklishin** [comment]
OK, so it turns out we already load the `rabbit` app (the server) to support `--offline` in `rabbitmq-plugins`, so this command can be ported more or less as it is in `3.6.x`.

**Comment by shatl** [comment]
Guys, quick question: once I ran `rabbitmqctl hipe_compile` and set `RABBITMQ_SERVER_CODE_PATH`, should I remove `hipe_compile=true` from rabbitmq.conf? 

Would it be enough to use pre-compiled binaries? 

Thanks

**Comment by lukebakken** [comment]
@shatl would you mind posting that question to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list? That way other people can learn from the answer. Thank you.
