### ISSUE TITLE
Provide an alternative to -setcookie

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-cli#180]
In 3.6, the Erlang cookie can be set via environment variable. For the CLI, it's `RABBITMQ_CTL_ERL_ARGS`, and for the broker it's `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS`.

In v3.7.0 Milestone 14 `-setcookie` in `RABBITMQ_CTL_ERL_ARGS` is no longer respected. After a quick chat with @hairyhum, it turns out that this is no longer supported in this generation of CLI tools: `-setcookie` works for the Erlang VM but not escripts. We believe that introducing a new environment variable, such as `RABBITMQ_COOKIE`, would solve this issue. A regular CLI switch is also an option.

Thoughts?

**Comment by michaelklishin** [comment]
Please make it `RABBITMQ_ERLANG_COOKIE`. We don't want to invent a new term.
