### ISSUE TITLE
Do we need to connect to the RMQ node before executing a command

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-cli#189]
The [`maybe_connect_to_rabbitmq`](https://github.com/rabbitmq/rabbitmq-cli/blob/master/lib/rabbitmqctl.ex#L167) function gets called before any command `run` function.
It can cause delays in command execution and for some commands is useless.
Do we even need this, or we can rely on `rpc` to connect to the node?

**Comment by michaelklishin** [comment]
We can add a function to the command interface that indicates whether a command is "local", and if it is, or `--offline` is used, avoid connecting.

**Comment by hairyhum** [comment]
I wonder if we need to do that in any commands, because `rpc:call` will connect to the node anyway.

**Comment by michaelklishin** [comment]
@hairyhum then let's drop it.
