### ISSUE TITLE
Consider restoring a way to list plugins without RabbitMQ node running

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-cli#219]
We've seen this change cause inconvenience in rabbitmq-server-boshrelease as well as for Docker image maintainers: https://github.com/docker-library/rabbitmq/issues/183#issuecomment-327271715.

Perhaps the 3.6.x behavior should be restored for `list`.

**Comment by gerhard** [comment]
Unless @hairyhum or @dumbbell can think of a really good reason why this is a bad idea, I support preserving the 3.6.x behaviour in 3.7.x

**Comment by michaelklishin** [comment]
We have a `-plugins list` test that says:

> test "will report list of plugins from file for stopped node"

so sounds like the change was unintentional.
