### ISSUE TITLE
SetParameterCommand overwrites vhost argument

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-cli#232]
See rabbitmq/rabbitmq-server#1446

Basically, [this line](https://github.com/rabbitmq/rabbitmq-cli/blob/master/lib/rabbitmq/cli/ctl/commands/set_parameter_command.ex#L24) should have the arguments reversed to `Map.merge`, as the items in the second argument are used to overwrite the first.

**Comment by michaelklishin** [comment]
Good catch.
