### ISSUE TITLE
Only display the -t argument for commands that actually support it

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-cli#236]
Not all commands do (or even meaningfully can) use the timeout argument but it does show up in help causing confusion.

We'd like to localize the argument: move it to the commands that actually use it.

**Comment by lukebakken** [comment]
It seems like most commands do use `rabbit_misc:rpc_call` but some ignore the timeout value, as in [this case](https://github.com/rabbitmq/rabbitmq-cli/blob/master/lib/rabbitmq/cli/plugins/commands/list_command.ex#L113). I'm going to do a bit of review to see exactly which commands don't do any rpc at all.
