### ISSUE TITLE
rabbitmqctl streaming results require epmd port lookup

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-cli#237]
See the following mailing list thread: https://groups.google.com/d/topic/rabbitmq-users/OiiVP_RjP5A/discussion

Prior behavior:

* Start up 3-node `3.6.14` cluster.
* Run PerfTest so that a queue is created.
* Start Wireshark, have it listen on any interface, port `4369`
* Run `rabbitmqctl list_queues`. You will only see `EPMD_PORT2_REQ` requests for `rabbit*` nodes, not the node running `rabbitmqctl` itself. See the `epmd-4369-any-3-node-cluster-3.6.14.pcapng` file in the attached archive.

`3.7.2` behavior:

Run the same reproduction steps. You will see`EPMD_PORT2_REQ` requests for `rabbit*` nodes **and** for the node running `rabbitmqctl` itself.

[pcap.zip](https://github.com/rabbitmq/rabbitmq-cli/files/1668886/pcap.zip)

**Comment by fatmcgav** [comment]
@lukebakken Cheers for your persistence on identifying this. 

Just to add some context on this issue; If running RabbitMQ behind a firewall, configured as per http://www.rabbitmq.com/networking.html, the `rabbitmqctl list_queues` command exits with an error, and therefore commands that depend on successfully running `rabbitmqctl list_queues`, such as Puppet, error out.

**Comment by lukebakken** [comment]
The behavior we're seeing is due to the code in these places:

https://github.com/rabbitmq/rabbitmq-cli/blob/master/lib/rabbitmq/cli/ctl/rpc_stream.ex#L35-L58
https://github.com/rabbitmq/rabbitmq-cli/blob/master/lib/rabbitmq/cli/ctl/rpc_stream.ex#L85-L88

Basically, they are changes to allow streaming result sets back to rabbitmqctl for efficiency's sake.

**Comment by michaelklishin** [comment]
We've identified a potential regression => this is not yet merged into `v3.7.x`.

**Comment by lukebakken** [comment]
I will get the docs changes.
