### ISSUE TITLE
Table column headers are missing from result

### ISSUE THREAD

**Issue by luos** [rabbitmq/rabbitmq-cli#264]
Hi, 

In previous versions (3.6.x) there was a header on top of each table, for the commands found in `rabbitmqctl report`, for example: 

```
Connections:
pid	name	port	peer_port	host	peer_host	ssl	peer_cert_subject	peer_cert_issuer	peer_cert_validity	auth_mechanism	ssl_protocol	ssl_key_exchange	ssl_cipher	ssl_hash	protocol	user	vhost	timeout	frame_max	channel_max	client_properties	connected_at	recv_oct	recv_cnt	send_oct	send_cnt	send_pend	state	channels
<rabbit@host.2.334.0>	172.31.30.29:55610 -> 172.31.11.110:5672	5672	55610	172.31.11.110	172.31.30.29	false				PLAIN					{0,9,1}	user	/	60	131072	0	[]	1537886725142	154731689	4950691	3347336556	7353344	0	running	3
```

Now this seems to be missing:

```
Listing connections ...
<rabbit@host.1.3380.0>	172.28.89.149:49739 -> 172.28.89.145:5672	5672	172.28.89.145	49739	172.28.89.149	false								running	0	{0,9,1}	PLAIN	user	/	60	131072	0	[]	115142720	346870	2070437	172437	0	1536343886590

```

Not sure if it's deliberate, but it was easier to copy it into a sheet and analyse it. 

Maybe it was deliberate the headers could be added back for only the "report" command?

**Comment by lukebakken** [comment]
Thanks for reporting this. I don't think this change was deliberate - @hairyhum ?

**Comment by hairyhum** [comment]
I've somehow totally missed that. It can be reintroduced (maybe optionaly)

**Comment by lukebakken** [comment]
[161326468]

**Comment by michaelklishin** [comment]
Note that `list_*` commands in 3.7.x support CSV output via `--formatter=csv`. It does include a header row and should be the easiest option to import in many cases.

**Comment by luos** [comment]
Hi,

Thank you for the fix and for mentioning those flags, I did not know about them. 

Lajos

**Comment by michaelklishin** [comment]
To clarify: the lack of table headers was a bug introduced in the 3.7 cycle. We left a couple of suggestions in https://github.com/voxpupuli/puppet-rabbitmq/issues/740 for those who relied on this bug.

**Comment by paulrbr-fl** [comment]
> To clarify: the lack of table headers was a bug introduced in the 3.7 cycle. We left a couple of suggestions in [voxpupuli/puppet-rabbitmq#740](https://github.com/voxpupuli/puppet-rabbitmq/issues/740) for those who relied on this bug.

Hi @michaelklishin are you sure it was a bug in 3.7? I think it was already the behavior in 3.6:
```
> docker exec -ti rabbit-3.6.12 rabbitmqctl -q status | grep RabbitMQ
     [{rabbit,"RabbitMQ","3.6.12"},

> docker exec -ti rabbit-3.6.12 rabbitmqctl -q list_user_permissions guest
/       .*      .*      .*
```

**Comment by michaelklishin** [comment]
@paulrbr-fl you are not comparing apples to apples since you passing `-q`. Anyhow, in 3.7.10 there will be `-q`, `--no-table-headers` and `-s` which combines the two. Case closed.
