### ISSUE TITLE
Rabbitmqctl output change

### ISSUE THREAD

**Issue by benpollard** [rabbitmq/rabbitmq-cli#273]
With release version 3.7.9 rabbitmqctl -q list_users includes headings for user and tags. It seems counterintuitive to include headings when using a quiet flag. Is this intended behaviour? I imagine this is going to cause issues for people who are parsing the output. As an example, this change is not compatible with the rabbitmq puppet module.

**Comment by michaelklishin** [comment]
Yes, this is intentional. See https://github.com/rabbitmq/rabbitmq-cli/issues/264. `-q` is used to suppress the banner commands output and @dumbbell and I concluded that a separate flag should control the headers. Not outputting the headers was the unintentional change [in 3.7.0].

`rabbitmqctl list_queues --no-table-headers -q` will also omit the headers.

**Comment by lukebakken** [comment]
Yes, it is intended. `-q` suppresses informational headers like "Listing queues for vhost / ...". There is an undocumented argument `--no-table-headers` that will accomplish what you want (https://github.com/rabbitmq/rabbitmq-server/commit/20539a03c6302a71477de66d54982d31b3c2913e). We'll be sure to add that to the `help` output.

**Comment by michaelklishin** [comment]
I agree that this deserves a mention in both `--help` and the CLI documentation guide.

**Comment by ralfbosz** [comment]
The -q and --no-table-headers is not available for list_users !

**Comment by ralfbosz** [comment]
/usr/sbin/rabbitmqctl -no-table-headers -q list_users
Error (argument validation): Invalid options for this command:

Doesn't work on list_users !

**Comment by michaelklishin** [comment]
There were comments in this thread claiming that `-q` and `--no-table-headers` aren't supported by `list_users`. I tried to verify. Here are my findings:

```
./sbin/rabbitmqctl list_users
Listing users ...
user	tags
bunny_reader	[]
bunny_gem	[]
alt3	[]
guest	[administrator]
temp-user	[management]
alt-user	[]
```


```
./sbin/rabbitmqctl list_users -q                                                                                                                                                                                                                
user	tags
bunny_reader	[]
bunny_gem	[]
alt3	[]
guest	[administrator]
temp-user	[management]
alt-user	[]
```

```
./sbin/rabbitmqctl list_users -q --no-table-headers
bunny_reader	[]
bunny_gem	[]
alt3	[]
guest	[administrator]
temp-user	[management]
alt-user	[]
```
