### ISSUE TITLE
Create help and short command alias for "--no-table-headers"

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-cli#274]
See #264, #273 and https://github.com/rabbitmq/rabbitmq-website/issues/633.

**Comment by michaelklishin** [comment]
Something in `OptionParser`'s switch negation function relies on `String.replace/3` which in turn assumes that `string:replace/3` is available in OTP and it isn't in 19.x. Reverted the backport to 3.7.x until after OTP 19.x support is dropped.

**Comment by michaelklishin** [comment]
Accidentally discovered another OTP 19-incompatible change introduced recently: https://github.com/rabbitmq/rabbitmq-ct-helpers/commit/9f9d2bd614f43ac6a6e8e6371e20ee9595a97168.

`OptionParser` [does use String.replace/4](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/option_parser.ex#L510) but it still works on OTP 19.x (note: we use 1.6.6):

``` elixir
Erlang/OTP 19 [erts-8.3.5.4] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [lock-counting]

Interactive Elixir (1.6.6) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> String.replace("abc", "b", "1")
"a1c"
```

So I re-back ported this PR and so far [Concourse is happy](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.7.x/jobs/test-rabbitmq-server%3Act-cluster/builds/162) and so are my local tests.
