### ISSUE TITLE
3.8: a new "pre-node removal" command

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-cli#286]
With quorum queues, when a node hosting one of the Raft cluster members is removed using `rabbitmqctl forget_cluster_node`, there's a possibility that there will no longer be a quorum to confirm any operation on the queue. This means, for example, that the queue becomes undeletable unless its
member is also removed using `rabbitmq-queues remove_member`.

We need new "pre-removal" command, say, `rabbitmq-queues decomission_node`, that would do that for every quorum queue that has a given node on the member list.

**Comment by dcorbacho** [comment]
Addressed in https://github.com/rabbitmq/rabbitmq-cli/pull/318 with the new command `rabbitmq-queues grow`
