### ISSUE TITLE
3.8: a new "post-node addition" command

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-cli#287]
See #286 for the background. A command that adds a node as a Raft cluster member for every or a subset quorum queue after a node is added.

The newly added node will be added as a member to all Raft clusters or a subset.

We identified two scenarios:

 * A new node is expected to grow the number of replicas for a quorum queue
 * A new node is a replacement for another node

Which means two modes of operation:

 * "Repair" a QQ member set by adding a replica to the queues below their max replica count (if they have one). The exact logic of this is still under considration.
 * Add a new replica to all QQs.

We should perhaps support named-based filtering (similar to policies) to make it easy to apply the changes to only a subset of quorum queues.

**Comment by dcorbacho** [comment]
Addressed in https://github.com/rabbitmq/rabbitmq-cli/pull/318 with the new command `rabbitmq-queues grow`
