### ISSUE TITLE
Introduce a rate control flag to rabbitmqctl (for list_* commands)

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-cli#288]
Following the implemention of #62, there could be need to introduce some level of control to the rate at which information is returned and displayed when `rabbitmqctl` `list_*` commands are executed. 

For example during troubleshooting, controlled monitoring and inspection of a node's metadata like queues and bindings in real time, while the node is subject to other factors like queue declarations, publishes, e.t.c.

**Comment by michaelklishin** [comment]
The need for rate limiting hasn't come up so far (in 3 years). What is an interesting idea here is a way to interactively observe internal events, much like what `rabbitmq-event-exchange` exposes to messaging protocol clients. I will file another issue for that.
