### ISSUE TITLE
A command that continuously consumes internal broker events

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-cli#299]
See #288 for the original idea.

A command that continuously consumes internal broker events would be useful for certain troubleshooting and operations scenarios, much like what `rabbitmq-event-exchange` exposes to messaging protocol clients.

[168224266]

**Comment by dcorbacho** [comment]
@lukebakken I don't think the table formatting is possible, as there isn't a common structure for events. Each of them has a different number/type of entries.
