### ISSUE TITLE
rabbitmq-diagnostics command to retrieve N most recent log lines 

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-cli#325]
In many cases it would be convenient to retrieve logs via `rabbitmq-diagnostics` instead of looking for a log file location first. It also can be done remotely.

Related to #299.

**Comment by gerhard** [comment]
This is a great idea, love it!

**Comment by michaelklishin** [comment]
Backported to `v3.7.x`.
