### ISSUE TITLE
Provide a way to tail logs via rabbitmq-diagnostics

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-cli#326]
In many cases it would be convenient to retrieve logs via `rabbitmq-diagnostics` instead of looking for log file location first. It also can be done remotely. Unlike #325, this one is about tailing logs continuously.

Implementation likely will be closely related to #299.

**Comment by gerhard** [comment]
Too good!

**Comment by lukebakken** [comment]
I'd like to suggest a slightly simpler command that outputs log location(s) to then be used by `tail` or other commands.

```
# tail -f "$(rabbitmq-diagnostics can_haz_log_path)"
```

Although this would not allow for tailing remote logs but IMHO that's a bit out of scope for our toolset. My $0.02

**Comment by michaelklishin** [comment]
@lukebakken we have done something similar with `rabbitmq-plugins directories`, so this is also a good feature to have but as you pointed out, it can only work on the same host.

**Comment by michaelklishin** [comment]
Backported to `v3.7.x`.
