### ISSUE TITLE
Getting "FunctionClauseError" when running rabbitmq-plugins list      

### ISSUE THREAD

**Issue by Sgryt87** [rabbitmq/rabbitmq-cli#335]
-> plugins  rabbitmq-plugins list       
Listing plugins with pattern ".*" ...
** (FunctionClauseError) no function clause matching in RabbitMQCtl.format_error/3    
    
    The following arguments were given to RabbitMQCtl.format_error/3:
    
        # 1
        {:case_clause, {:error, {:missing_dependencies, [:eldap], [:rabbitmq_auth_backend_ldap]}}}
    
        # 2
        %{enabled: false, implicitly_enabled: false, longnames: false, minimal: false, node: :rabbit@localhost, timeout: :infinity, verbose: false}
    
        # 3
        RabbitMQ.CLI.Plugins.Commands.ListCommand
    
    (rabbitmqctl) lib/rabbitmqctl.ex:367: RabbitMQCtl.format_error/3
    (rabbitmqctl) lib/rabbitmqctl.ex:124: anonymous fn/5 in RabbitMQCtl.exec_command/2
    (rabbitmqctl) lib/rabbitmqctl.ex:45: RabbitMQCtl.main/1
    (elixir) lib/kernel/cli.ex:105: anonymous fn/3 in Kernel.CLI.exec_fun/2

**Comment by michaelklishin** [comment]
Please post your questions to rabbitmq-users in the future. This team does not use GitHub issues for queestions. Thank you.

Your Erlang installation is missing `eldap`, an LDAP client implementation.

**Comment by Sgryt87** [comment]
The issue was resolved once the homebrew updated a rabbitmq package to 3.7.14

**Comment by michaelklishin** [comment]
`eldap` does not ship with RabbitMQ, it's a part of Erlang/OTP. I suspect that Homebrew updated Erlang as well. Thanks for reporting back.
