### ISSUE TITLE
ctl delete_queue -u fails argument validation

### ISSUE THREAD

**Issue by sylr** [rabbitmq/rabbitmq-cli#339]
Version: 3.7.14

```
root@rabbitmq2-vm1:~# rabbitmqctl delete_queue --vhost="/" myqueue  -u
Error (argument validation): Invalid options for this command:
-u :
Arguments given:
        delete_queue --vhost=/ myqueue -u

Usage

rabbitmqctl [--node <node>] [--longnames] [--quiet] delete_queue queue_name [--if_empty|-e] [--if_unused|-u] [--timeout <timeout>]
```

**Comment by michaelklishin** [comment]
I could reproduce with `-u` but `--if-unused` does work for me.

**Comment by sylr** [comment]
@michaelklishin it says `--if_unused` with un underscore in the help message.

**Comment by michaelklishin** [comment]
@sylr I know, that also will be corrected. All other switches in every RabbitMQ CLI tool use --kebab-case.

**Comment by michaelklishin** [comment]
It was a typo in switch alias definition. Thanks for reporting it, that command hasn't seen much attention in over 2 years.
