### ISSUE TITLE
Output of the set_parameter command can be misleading

### ISSUE THREAD

**Issue by Whitespirit0** [rabbitmq/rabbitmq-cli#376]
Hello,

I think there is an inversion between parameter name and component in the `set_parameter` command output.

For example the command:
```
[root@hostname ~]# rabbitmqctl set_parameter federation-upstream my-upstream '{"uri":"amqp://user:pass@host","max-hops":1}'
```
Produces the output:
```
Setting runtime parameter "federation-upstream" for component "my-upstream" to "{"uri":"amqp://user:pass@host","max-hops":1}" in vhost "/" ...
```
If I understand correctly the [parameters doc](https://www.rabbitmq.com/parameters.html#parameter-management), I would have expected the following output:
```
Setting runtime parameter "my-upstream" for component "federation-upstream" to "{"uri":"amqp://user:pass@host","max-hops":1}" in vhost "/" ...
```

Here is my environment:
* RabbitMQ server: 3.7.17
* Erlang: 22.0.7
* OS: Oracle Linux 7.6

Thanks for your attention.

**Comment by michaelklishin** [comment]
It looks like it. Would you like to contribute a PR? [Here's where](https://github.com/rabbitmq/rabbitmq-cli/blob/master/lib/rabbitmq/cli/ctl/commands/set_parameter_command.ex#L72) the command banner is computed :)

Thank you for your ongoing contributions.

**Comment by Whitespirit0** [comment]
Sure, I'll try to submit one today.
