### ISSUE TITLE
rabbitmqctl.bat parsing arguments starting with "-" (minus) fails

### ISSUE THREAD

**Issue by inikulshin** [rabbitmq/rabbitmq-cli#393]
Initial issue was inability to set password, staring with `-`

`rabbitmqctl.bat change_password user "-password"`

But the same issue exist for other commands, e.g.

`rabbitmqctl.bat delete_queue "-queue_name"`

**Comment by inikulshin** [comment]
The output is:

```
Error (argument validation): Invalid options for this command:
-p :
-a :
-w :
-o :
-r :
-d :
Arguments given:
        change_password user -password
```

**Comment by inikulshin** [comment]
Another, not related suggestion: to have `change_password_hash` command (also `add_user` with `password_hash`)

**Comment by michaelklishin** [comment]
Having a hyphen (`-`) at the beginning of a command line argument is a long time convention for passing options. While this varies somewhat between operating systems, shells and programming languages, all `-v`, `-version` and `--version` are valid option examples. `-fan` can further be interpreted as `-f -a -n` in some environments.

These conventions have been around for decades. While Windows doesn't follow them, I don't see a way for the CLI argument parser we use to really tell between a positional value that starts with a hyphen and an option *and* cover all of the above conventions on other platforms.

Use passwords that do not begin with a hyphen.

**Comment by michaelklishin** [comment]
As for providing a password hash, HTTP API [allows for that](https://www.rabbitmq.com/passwords.html#computing-password-hash) and it is moderately painful to use. We see little interest in adding a command that would do the same.

As of #365, it is possible to enter password values via standard input so that it can be omitted from  command line arguments that can be spoofed in some environments.

Lastly, there's a way to [preconfigure a node](https://www.rabbitmq.com/management.html#load-definitions) including users.

**Comment by inikulshin** [comment]
Well, probably this limitation should be added to https://www.rabbitmq.com/rabbitmqctl.8.html documentation (and other scripts?)

Not only for passwords, but for **all** commands (on Windows)

> While Windows doesn't follow them

There are a lot of Windows applications complying http://docopt.org/ standard. RabbitMQ can be one them - with the **right** CLI argument parser.

**Comment by lukebakken** [comment]
@michaelklishin the common convention is to use `--` to signal the end of argument input. I bet we could add that to the CLI relatively easily.

I frequently use `--` when I use `grep`, like this:

```
find . -type f -name '*.erl' -exec egrep -- '-behaviour' {} +
```

**Comment by michaelklishin** [comment]
@lukebakken and it is supported by Elixir's `OptionParser` but that won't help with `--option` values that begin with a hyphen. Those are considered to be shortcut to a list of short options:

```
iex(1)> OptionParser.parse(["--key", "value", "--", "abc"], strict: [key: :string])
{[key: "value"], ["abc"], []}
iex(2)> OptionParser.parse(["--key", "-value", "--", "abc"], strict: [key: :string])
{[], ["abc"],
 [
   {"--key", nil},
   {"-v", nil},
   {"-a", nil},
   {"-l", nil},
   {"-u", nil},
   {"-e", nil}
 ]}
```

so `-value` is treated as `-v -a -l -u -e` which is how it works with some tools and on some platforms.

**Comment by michaelklishin** [comment]
@inikulshin sorry but we won't be developing our own command line argument parser. We use the standard one in Elixir, which does support the `--speed=<kn>` example from the docopt page:

```
iex(3)> OptionParser.parse(["--key=-value", "--", "abc"], strict: [key: :string])
{[key: "-value"], ["abc"], []}
```

so maybe `--option="-value"` is what you should use. Any CLI parser contributions should be proposed and directed to Elixir, not these CLI tools.

**Comment by michaelklishin** [comment]
Also while we consider CLI tools to be largely underdocumented (as far as introductory tutorials), we did not invent any of these conventions, so documenting them also feels like a complete overkill. But we will document how options with "less regular" values can be passed.

**Comment by michaelklishin** [comment]
@lukebakken I now see what you mean. For `change_password` and similar commands where such values are positional arguments, yes, I think that's the answer. `OptionParser` already supports the `--` separator, as it does `--option={value}` pairs with an equality sign.

**Comment by michaelklishin** [comment]
``` shell
rabbitmqctl add_user "example3" "-example3"
Error (argument validation): Invalid options for this command:
-e :
-x :
-a :
-m :
-p :
-e :
Arguments given:
	add_user example3 -example3

Usage

rabbitmqctl [--node <node>] [--longnames] [--quiet] add_user <username> <password>
rabbitmqctl add_user -- "example3" "-example3"                                                                                                                                                                                 
Adding user "example3" ...
```

@inikulshin does the 2nd example above look like what you were trying to do?

**Comment by lukebakken** [comment]
@michaelklishin I thought `OptionParser` might already take care of that case, and it does. @inikulshin please use this command:

```
>.\rabbitmqctl.bat change_password guest -- -password
Changing password for user "guest" ...

>.\rabbitmqctl.bat authenticate_user guest -- -password
Authenticating user "guest" ...
Success
```

**Comment by inikulshin** [comment]
@lukebakken, @michaelklishin thanks a lot!

I thinks this one (`--`) **must** be documented.

@lukebakken, I quoted -password because real passwords are auto-generated and can contain other special characters.


As for providing a password hash, HTTP API can be used only when administrator user exist and its credentials are known. But I agree, this is minor, and suggested "preconfigure a node" solution is the best.

**Comment by michaelklishin** [comment]
@inikulshin well, again, it's not something we invented. The positional argument separator has been around in at least 2003 (and likely before that).

**Comment by michaelklishin** [comment]
I've added a new section to the main CLI tools guide. I'm not sure if we should change the command's usage hint to something like

```
add_user -- <username> <password>
```

as we don't do that for other commands and the separator can be confusing (and not necessary for other commands or even `add_user`/`change_password` most of the time)

**Comment by lukebakken** [comment]
FWIW, `grep --help` does not mention `--`: [gnu-grep-3.3-help.txt](https://github.com/rabbitmq/rabbitmq-cli/files/4056882/gnu-grep-3.3-help.txt)
