### ISSUE TITLE
Add units to rabbitmqctl status

### ISSUE THREAD

**Issue by bdshroyer** [rabbitmq/rabbitmq-cli#4]
Currently the `status` command prints all numerical units as-is, with no units associated. We should get some units associated with the output.

NOTE: this may be best accomplished by in-lining transformations to the raw `result` rather than directly modifying the printing code.

**Comment by michaelklishin** [comment]
`rabbitmq-diagnostics memory_breakdown` already does this:

```
Reporting memory breakdown on node rabbit@mercurio...
allocated_unused: 0.0524 gb (29.38%)
other_proc: 0.0431 gb (24.17%)
code: 0.0239 gb (13.38%)
plugins: 0.0234 gb (13.13%)
other_system: 0.0233 gb (13.04%)
other_ets: 0.0068 gb (3.82%)
binary: 0.0024 gb (1.34%)
mgmt_db: 0.0013 gb (0.74%)
atom: 0.0012 gb (0.66%)
metrics: 0.0003 gb (0.15%)
queue_procs: 0.0001 gb (0.07%)
mnesia: 0.0001 gb (0.07%)
msg_index: 0.0001 gb (0.05%)
connection_other: 0.0 gb (0.01%)
connection_readers: 0.0 gb (0.0%)
connection_writers: 0.0 gb (0.0%)
connection_channels: 0.0 gb (0.0%)
queue_slave_procs: 0.0 gb (0.0%)
reserved_unallocated: 0.0 gb (0.0%)
```

Instead of changing `status` we are adding more specific commands that usually offer better formatting and support for machine-readable formats.
