### ISSUE TITLE
Provide a way to evaluate a file with code

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-cli#438]
Currently you are forced to get shell quoting exactly right, which is very difficult due to the interaction between Erlang syntax and shell quoting rules. On Windows, this becomes even more difficult.

The `eval` subcommand should be able to read Erlang clauses from a file and execute them.

**Comment by michaelklishin** [comment]
I think a new command, e.g. `eval_file [path]` would be best.

**Comment by gerhard** [comment]
Would it make sense for `rabbitmqctl eval` to work with `STDIN`?

If yes, then this could be used in a number of ways, including part of a UNIX pipeline:

```
[SOME CODE] | [MORE CODE] | rabbitmqctl eval

cat FILE | rabbitmqctl eval

rabbitmqctl eval < FILE

rabbitmqctl eval <<< [STRING_AS_STDIN]
```

By the way, how does `STDIN` work on Windows?

**Comment by michaelklishin** [comment]
Supporting stdin is also a good idea.

**Comment by lukebakken** [comment]
> By the way, how does STDIN work on Windows

`cmd.exe` supports pipes, and powershell probably has better options, but the best way on Windows will be to read a file.

**Comment by michaelklishin** [comment]
This is why I think we should both add a new command to eval a file and support stdin for the command we have.
