### ISSUE TITLE
Add `--all` to `rabbitmqctl enable_feature_flag`

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/rabbitmq-cli#455]
It would be convenient to have a single command to enable all feature flags supported by a cluster. Currently all feature flags have to be enabled individually.

**Comment by mkuratczyk** [comment]
I've submitted a PR for this feature. I also have a corresponding docs commit (https://github.com/mkuratczyk/rabbitmq-website/commit/873be2972ec54ea40c2fb469c48ac7a73ba22894) but I'm not sure which branch to PR it to (I guess that depends on whether this PR is approved)

**Comment by michaelklishin** [comment]
@mkuratczyk it will only ship in the next patch release, so`stable`
